
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\TestTrust\Tkinter-Designer-master\Source\assets\frame9")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    22.0,
    0.0,
    1494.0,
    89.0,
    fill="#000000",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    95.0,
    863.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    95.0,
    339.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1345.0,
    863.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1345.0,
    339.0,
    image=image_image_4
)

canvas.create_rectangle(
    55.0,
    111.0,
    355.0,
    187.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    84.0,
    125.0,
    anchor="nw",
    text="Test-Trust team:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_text(
    355.0,
    221.0,
    anchor="nw",
    text="NCTU Information Technology networking Track",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_rectangle(
    231.0,
    306.0,
    481.0,
    556.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    891.0,
    620.0,
    1141.0,
    870.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    561.0,
    306.0,
    811.0,
    556.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    891.0,
    296.0,
    1141.0,
    546.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    231.0,
    620.0,
    481.0,
    870.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    561.0,
    620.0,
    811.0,
    870.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
