
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\TestTrust\Tkinter-Designer-master\Source\assets\frame7")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    22.0,
    0.0,
    1494.0,
    89.0,
    fill="#000000",
    outline="")

canvas.create_text(
    242.0,
    106.0,
    anchor="nw",
    text="Thanks For The Previous Informations, Now Let’s Create The Exam :)",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_text(
    601.0,
    169.0,
    anchor="nw",
    text="Question Type?",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_text(
    191.0,
    333.0,
    anchor="nw",
    text="Enter your Question No. 1",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    191.0,
    563.0,
    anchor="nw",
    text="Would you like us to do the correction for you?",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    191.0,
    683.0,
    anchor="nw",
    text="If Yes, please provide us with the answer to the previous question",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    754.0,
    568.0,
    anchor="nw",
    text="Yes",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 20 * -1)
)

canvas.create_text(
    866.0,
    568.0,
    anchor="nw",
    text="No",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 20 * -1)
)

canvas.create_rectangle(
    819.0,
    568.0,
    849.0,
    598.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    930.0,
    568.0,
    960.0,
    598.0,
    fill="#D9D9D9",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    716.0,
    455.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=199.0,
    y=394.0,
    width=1034.0,
    height=120.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    709.0,
    250.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=600.0,
    y=226.0,
    width=218.0,
    height=46.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    716.0,
    818.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=199.0,
    y=757.0,
    width=1034.0,
    height=120.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=552.0,
    y=940.0,
    width=335.0,
    height=62.1171875
)

canvas.create_rectangle(
    1284.0,
    260.0,
    1430.0,
    1006.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    24.0,
    111.0,
    158.0,
    797.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    603.0,
    235.0,
    anchor="nw",
    text="Choose one",
    fill="#C4C4C4",
    font=("AbrilFatface Regular", 20 * -1)
)

canvas.create_rectangle(
    796.0,
    241.0,
    816.0,
    256.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
