
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\TestTrust\Tkinter-Designer-master\Source\assets\frame10")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    22.0,
    0.0,
    1494.0,
    89.0,
    fill="#000000",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1237.0,
    241.0,
    image=image_image_1
)

canvas.create_rectangle(
    17.0,
    110.0,
    586.0,
    988.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    27.0,
    138.0,
    anchor="nw",
    text="Test Trust is an innovative way to implement exams, changing the traditional paper examination methods to a more secured and automated methods providing confidentiality of the data including the exams, student and engineers data and students grades \nas well as an authentication system using biometric access using finger print and full control over the students activity during the exam\nthis advanced examination method is brought to you by NCTU IT 4th year networking  team  .",
    fill="#000000",
    font=("Inder Regular", 24 * -1)
)

canvas.create_rectangle(
    793.0,
    130.0,
    1043.0,
    701.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1099.0,
    397.0,
    1432.0,
    751.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    789.0,
    748.0,
    1172.0,
    1013.0,
    fill="#D9D9D9",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1328.0,
    960.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    686.0,
    553.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
