
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\TestTrust\Tkinter-Designer-master\Source\assets\frame5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    90.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    25.0,
    471.0,
    1415.0,
    1000.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    48.0,
    125.0,
    452.0,
    175.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    20.0,
    175.0,
    1410.0,
    435.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    20.0,
    175.0,
    1410.0,
    435.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1351.0,
    182.0,
    1380.0,
    427.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    33.000001192016256,
    185.00000065791795,
    1327.0000038146973,
    245.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1249.0,
    191.0,
    1296.0,
    238.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1249.0,
    273.0,
    1296.0,
    320.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1249.0,
    354.0,
    1296.0,
    401.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    55.99997961895941,
    497.4738917131306,
    404.0000305175781,
    980.473876953125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    410.99997940797556,
    491.9999863692108,
    1386.0,
    980.0,
    fill="#000000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    682.5,
    554.473876953125,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=587.0,
    y=528.473876953125,
    width=191.0,
    height=50.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1119.0,
    647.473876953125,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=880.0,
    y=621.473876953125,
    width=478.0,
    height=50.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1119.0,
    755.473876953125,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=880.0,
    y=729.473876953125,
    width=478.0,
    height=50.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    682.5,
    628.973876953125,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=587.0,
    y=603.473876953125,
    width=191.0,
    height=49.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    682.5,
    703.473876953125,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=587.0,
    y=677.473876953125,
    width=191.0,
    height=50.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    682.5,
    778.473876953125,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=587.0,
    y=752.473876953125,
    width=191.0,
    height=50.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    682.5,
    852.473876953125,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=587.0,
    y=826.473876953125,
    width=191.0,
    height=50.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    682.5,
    927.473876953125,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=587.0,
    y=901.473876953125,
    width=191.0,
    height=50.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=88.0,
    y=852.682861328125,
    width=265.0,
    height=64.34683227539062
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=999.0,
    y=852.682861328125,
    width=265.0,
    height=64.34683227539062
)

canvas.create_text(
    76.0,
    542.473876953125,
    anchor="nw",
    text="Exam Subject:   CCNA",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    76.0,
    615.473876953125,
    anchor="nw",
    text="Year:   4TH",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    76.0,
    691.473876953125,
    anchor="nw",
    text="Exam Date: 25/4/2025",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_rectangle(
    33.000001192016256,
    267.00000065791795,
    1327.0000038146973,
    327.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    33.000001192016256,
    349.00000065791795,
    1327.0000038146973,
    409.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1351.0,
    188.0,
    1380.0,
    229.0,
    fill="#000000",
    outline="")

canvas.create_text(
    64.0,
    196.0,
    anchor="nw",
    text="CCNA",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    435.0,
    536.473876953125,
    anchor="nw",
    text="Subject",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    873.0,
    568.473876953125,
    anchor="nw",
    text="Question",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    873.0,
    682.473876953125,
    anchor="nw",
    text="Answer",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    435.0,
    686.473876953125,
    anchor="nw",
    text="Year",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    435.0,
    752.473876953125,
    anchor="nw",
    text="Duration",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    435.0,
    838.473876953125,
    anchor="nw",
    text="Mark",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    435.0,
    910.473876953125,
    anchor="nw",
    text="Date",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    435.0,
    612.473876953125,
    anchor="nw",
    text="Department",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    634.0,
    196.0,
    anchor="nw",
    text="DR.mohamed",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    648.0,
    280.0,
    anchor="nw",
    text="DR.Eman",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    645.0,
    362.0,
    anchor="nw",
    text="DR.Amani",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    67.0,
    280.0,
    anchor="nw",
    text="Big Data",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    211.0,
    198.0,
    anchor="nw",
    text="4TH",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    207.0,
    280.0,
    anchor="nw",
    text="4TH",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    207.0,
    362.0,
    anchor="nw",
    text="4TH",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    507.0,
    196.0,
    anchor="nw",
    text="30 ST",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    507.0,
    280.0,
    anchor="nw",
    text="20 ST",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    506.0,
    362.0,
    anchor="nw",
    text="25 ST",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    830.0,
    196.0,
    anchor="nw",
    text="30 Q/A",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    830.0,
    280.0,
    anchor="nw",
    text="15 Q/A",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    830.0,
    362.0,
    anchor="nw",
    text="20 Q/A",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    976.0,
    196.0,
    anchor="nw",
    text="IT",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    976.0,
    280.0,
    anchor="nw",
    text="IT",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    976.0,
    365.0,
    anchor="nw",
    text="IT",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    319.0,
    196.0,
    anchor="nw",
    text="25/4/2025",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    319.0,
    280.0,
    anchor="nw",
    text="28/4/2025",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    319.0,
    364.0,
    anchor="nw",
    text="28/4/2025",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    58.0,
    348.0,
    anchor="nw",
    text="Network Admin",
    fill="#FFFFFF",
    font=("AbrilFatface Regular", 24 * -1)
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    1005.0,
    149.0,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=896.0,
    y=125.0,
    width=218.0,
    height=46.0
)

canvas.create_text(
    899.0,
    134.0,
    anchor="nw",
    text="Provide a Filter",
    fill="#C4C4C4",
    font=("AbrilFatface Regular", 20 * -1)
)

canvas.create_rectangle(
    1077.0,
    130.0,
    1115.0,
    168.0,
    fill="#FFFFFF",
    outline="")

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    990.0,
    528.4738464355469,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=881.0,
    y=503.4738464355469,
    width=218.0,
    height=48.0
)

canvas.create_text(
    884.0,
    512.473876953125,
    anchor="nw",
    text="Filter By Q. no.",
    fill="#C4C4C4",
    font=("AbrilFatface Regular", 20 * -1)
)

canvas.create_rectangle(
    1062.0,
    509.4738464355469,
    1100.0,
    547.4738464355469,
    fill="#FFFFFF",
    outline="")

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    1249.0,
    528.4738464355469,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=1140.0,
    y=503.4738464355469,
    width=218.0,
    height=48.0
)

canvas.create_text(
    1143.0,
    512.473876953125,
    anchor="nw",
    text="Filter By Q.Type",
    fill="#C4C4C4",
    font=("AbrilFatface Regular", 20 * -1)
)

canvas.create_rectangle(
    1321.0,
    509.4738464355469,
    1359.0,
    547.4738464355469,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    1047.0,
    362.0,
    anchor="nw",
    text="View Details",
    fill="#000000",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    1047.0,
    278.0,
    anchor="nw",
    text="View Details",
    fill="#000000",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    1043.0,
    198.0,
    anchor="nw",
    text="View Details",
    fill="#000000",
    font=("AbrilFatface Regular", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
