
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\TestTrust\Tkinter-Designer-master\Source\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    521.0,
    130.0,
    1206.0,
    964.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    22.0,
    32.0,
    1494.0,
    155.0,
    fill="#D9D9D9",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=10.571428298950195,
    y=22.39672088623047,
    width=279.20635986328125,
    height=47.84754180908203
)

canvas.create_text(
    18.0,
    573.1524658203125,
    anchor="nw",
    text="Email:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_text(
    18.0,
    643.0,
    anchor="nw",
    text="ID:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_text(
    18.0,
    496.8000183105469,
    anchor="nw",
    text="Name:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 30 * -1)
)

canvas.create_text(
    569.0,
    158.0,
    anchor="nw",
    text="Departments:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    569.0,
    392.0,
    anchor="nw",
    text="Departments:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    569.0,
    230.0,
    anchor="nw",
    text="Years:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_text(
    569.0,
    303.0,
    anchor="nw",
    text="No. Of Exams published this year:",
    fill="#EB5E28",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_rectangle(
    1299.68310546875,
    10.448789596557617,
    1370.920181274414,
    70.2657642364502,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    82.0,
    115.0,
    414.0,
    452.0,
    fill="#000000",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=80.0,
    y=777.0,
    width=335.0,
    height=62.1171875
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=80.0,
    y=884.0,
    width=335.0,
    height=62.1171875
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1334.0,
    566.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    457.0,
    415.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    53.0,
    149.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1080.0,
    200.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    685.0,
    894.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1136.0,
    708.0,
    image=image_image_6
)
window.resizable(False, False)
window.mainloop()
